info:
  component: Gateway Service
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    account: 
      path: /account/**
      serviceId: account-service
    customer: 
      path: /customer/**
      serviceId: customer-service
    auth:
      path: /uaa/**
      serviceId: authentication-service
      sensitiveHeaders: 
      stripPrefix: false          

security:
  user:
    name: root
    password: password
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      authorized-grant-types: authorization_code,refresh_token,implicit,password,client_credentials
      scope: openid
    resource:
     userInfoUri: http://localhost:9999/uaa/user
     preferTokenInfo: false
#   sso:
#     loginPath: 
    
#proxy:
#  auth:
#    routes:
#      account: oauth2
#      customer: oauth2
#      auth: passthru
      
ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG