server:  
  port: ${PORT:8080}

spring:  
  application:
    name: admin-service

eureka:  
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    
management:
  security:
    enabled: false